[package]
name = "window_relocator"
version = "0.1.0"
authors = ["nnnnusui"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
csv = "1.1"
[dependencies.winapi]
version = "0.3"
features = ["winuser"]
